language: generic

addons:
  apt:
    packages: libcurl4-openssl-dev

branches:
  only:
    - master

jobs:
  include:
    - state: build
      script: bash ./build.sh
      on:
        branch: master

